dist: focal

language: php

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - slapd
      - ldap-utils
      - conntrack

env:
  global:
    - TESTS_LAMINAS_LDAP_ONLINE_ENABLED=true
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"

matrix:
  fast_finish: true
  include:
    - php: 7.3
      dist: bionic
      env:
        - DEPS=lowest
    - php: 7.3
      dist: bionic
      env:
        - DEPS=latest
        - CS_CHECK=true
        - TEST_COVERAGE=true
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
      env:
        - DEPS=latest

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - sudo .ci/config_iptables.sh

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $LEGACY_DEPS != '' ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - stty cols 120 && composer show

before_script:
  - .ci/OpenLDAP_run.sh
  - .ci/load_fixtures.sh

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi

notifications:
  email: false
